name: Org CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  core:
    uses: No-Gas-Labs-Official/no-gas-labs-governance/.github/workflows/ci-core.yml@ef2819948f2f9aca1ecd7ffcc7cfeea4c2f3f9d7

  security:
    uses: No-Gas-Labs-Official/no-gas-labs-governance/.github/workflows/security-core.yml@ef2819948f2f9aca1ecd7ffcc7cfeea4c2f3f9d7

  classification:
    uses: No-Gas-Labs-Official/no-gas-labs-governance/.github/workflows/repo-classification-check.yml@ef2819948f2f9aca1ecd7ffcc7cfeea4c2f3f9d7
